
- hosts: all
  gather_facts: False
  vars_files:
    - destination-servers.yaml
  tasks:
    - name: check if connection to destination servers and ports are accessible
      wait_for:
        host: "{{ item.host }}"
        port: "{{ item.port }}"
        state: started
        delay: 0
        timeout: 2
      loop: "{{ destinationservers  }}"
